Introducing link feature (from v1.3.11 to v1.3.12)
lostdesign/linked pull request #108
Opened 2021-11-15 09:11 UTC by richardevcom

@lostdesign you were too fast and I couldn't create pull request fro v1.3.11 tagged to my v1.3.12 tagged version, so I am requesting this on your main branch 😆

2021-11-15 09:42 UTC, lostdesign requested changes
Judging based on the gif, it'd be better if the link opened directly on click don't you think?

2021-11-15 09:48 UTC, richardevcom commented
> Judging based on the gif, it'd be better if the link opened directly on click don't you think?

```js
Link({
  openOnClick: false,
})
```
is not extendable, so we need `on` `click` event listener directly in tiptap editor.. which honestly I didn't find in their solution. My guess it will have to be done within Vue.js scope.

2021-11-15 11:50 UTC, richardevcom commented
updated https://github.com/lostdesign/linked/pull/108/commits/7dc7dc8da59bcb0d81852fb56ede458dbcfcc4f5

2021-11-19 16:06 UTC, lostdesign requested changes
See the other commands as well as:
Opening directly on click seems a bit weird actually - I think it is better to have cmd/ctrl+click to open them. 

Other than that looks good, I'd contribute to your branch to work on the design as that would need to be adjusted before release. But we've discussed that - I might get to that end of November however.

2021-11-19 16:46 UTC, richardevcom commented on src/assets/css/tailwind.css
> +.hidden {
lol. for a moment I think I just didn't switch to `tailwind.config.js` for dev env.

2021-11-19 16:48 UTC, richardevcom commented on src/assets/icons/open-link.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 22" height="15px"><path d="M21,11a1,1,0,0,0-1,1v7a1,1,0,0,1-1,1H3a1,1,0,0,1-1-1V3A1,1,0,0,1,3,2h7a1,1,0,0,0,0-2H3A3,3,0,0,0,0,3V19a3,3,0,0,0,3,
https://www.iconfinder.com free icon (it has https://creativecommons.org/licenses/by-nc/3.0/ Non Commercial license so.. I guess I will draw my own quickly).

2021-11-19 16:48 UTC, richardevcom commented on src/assets/icons/unlink.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 21.95" height="15"><path d="M18.84,3.24a2.44,2.44,0,0,0-3.46,0L11.93,6.7a1.24,1.24,0,0,1-1.73,0A1.22,1.22,0,0,1,10.2,5l3.45-3.46a4.89,4.89,0,0,
https://www.iconfinder.com free icon (it has https://creativecommons.org/licenses/by-nc/3.0/ Non Commercial license so.. I guess I will draw my own quickly).

2021-11-19 16:49 UTC, richardevcom commented on src/background.js
> +ipcMain.on('openurl', (event, arg) => {
On quick look I thought those are Vuex store related methods 👀 will do.

2021-11-19 16:53 UTC, lostdesign commented on src/assets/icons/open-link.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 22" height="15px"><path d="M21,11a1,1,0,0,0-1,1v7a1,1,0,0,1-1,1H3a1,1,0,0,1-1-1V3A1,1,0,0,1,3,2h7a1,1,0,0,0,0-2H3A3,3,0,0,0,0,3V19a3,3,0,0,0,3,
No need, we can use iconic.app

2021-11-19 16:53 UTC, richardevcom commented
> 
Yeah let's see who from us both will do it first 😄 In future `on` `click` and `cmd` + `click` should be set as setting for user to select from. For now I do agree `cmd` + `click` is more user friendly.

About that layout/UI - I'll ask around for suggestions.

Let me fix suggestions above and "p.r." final-final-final branch 😄

2022-03-02 20:48 UTC, lostdesign commented
Closing meanwhile as linked progressed so much.

2022-03-02 20:48 UTC, closed without merging