Fixed the issue: About window does not show on linux
lostdesign/linked pull request #141
Opened 2022-03-02 17:32 UTC by ludovici-philippus

I created a validation to check if the OS is Linux, if yes, it will create a dialog box with the message:
"Version: (version)
Copyright © 2022 André Weller"
Unfortunately, I couldn't add the logo, even adding it to the options of showMessageBox, it just doesn't shows up.
(Resending it, but edited from nano, instead of Vim, I think this way it won't change the line breaks etc)

2022-03-02 20:06 UTC, lostdesign requested changes

2022-03-02 20:06 UTC, lostdesign commented on src/background.js
> +	async click() {
These two lines seem a bit off formatting wise.

2022-03-02 20:06 UTC, lostdesign commented on src/background.js
> +              detail: "Version " + version + " (" + version + ")\nCopyright © 2022 André Weller",
Can you take the Name from the package.json as well?

2022-03-02 20:06 UTC, lostdesign commented on src/background.js
> +              icon: "../appIcon/icon.png"
You mentioned that this is not working, should this not be removed then? IIRC setting the icon should work across all OS though.

2022-03-02 20:27 UTC, ludovici-philippus commented on src/background.js
> +	async click() {
Yeah, they are. I will fix it, I changed these using nano, which makes it a little strange

2022-03-02 20:40 UTC, ludovici-philippus commented on src/background.js
> +              icon: "../appIcon/icon.png"
I think it is a thing with my Artix Linux, none of the icons (warning, info etc) seem to show up. I will investigate to try to fix it

2022-03-02 21:34 UTC, ludovici-philippus commented on src/background.js
> +              icon: "../appIcon/icon.png"
Ok, fixed it! The error was the way I was taking the icon.
I writed: icon: "../appIcon/icon.png", when the right way were: 
icon: path.join(__dirname, '..', "appIcon/icon.png").
Now the icon is showing on about window
![image](https://user-images.githubusercontent.com/37634205/156453374-5f406cf6-8b1c-459f-b865-92dbecf434ac.png)

2022-03-02 21:37 UTC, lostdesign commented on src/background.js
> +              icon: "../appIcon/icon.png"
Why is "linked" so far off to the right? Weird. Electron sometimes sure is magic lol

2022-03-02 21:49 UTC, ludovici-philippus commented on src/background.js
> +              icon: "../appIcon/icon.png"
Lol, I think it tried to separate the logo and the text in two boxes and aligned the "linked" to the center of the second box, which should be, more or less, 60% of the Message Box, then it seems to be far off to the right. 
I think, if the "Version 1.4.8 (1.4.8)" was aligned to the center, it will be a little better and the "linked" wouldn't be so weird; however, I don't know if it can be done using the dialog.showMessageBox

2022-03-03 14:21 UTC, lostdesign commented
@ludovici-philippus can you send a current screenshot of the current message box design? Or is it still as above?

2022-03-03 18:17 UTC, ludovici-philippus commented
> 

It it still as above

2022-03-04 09:32 UTC, lostdesign commented
Since it is still as above I'd rather remove the about on Linux or have a better design for it. The dialogMessage looks quite off. Would you be interested in checking ways to get a better design?

If not, just wrap that entry and don't display `about` on Linux builds.

2022-03-04 18:36 UTC, ludovici-philippus commented
> Since it is still as above I'd rather remove the about on Linux or have a better design for it. The dialogMessage looks quite off. Would you be interested in checking ways to get a better design?
> 
> If not, just wrap that entry and don't display `about` on Linux builds.

I think there's a way to get a better design. It is possible to open an html file as a pop up, in the html it is possible to use javascript and css to better customization, I will try to do it, this way the about window can be more homogeneous

2022-10-01 10:28 UTC, lostdesign commented
Closing this as the PR is stale. Feel free to open a new PR with the requested changes once ready.

2022-10-01 10:28 UTC, closed without merging