Added Bengali locale
lostdesign/linked pull request #168
Opened 2022-09-16 14:37 UTC by soumyatheman

I have added bengali locale. Also would like to edit and make some changes in Hindi locale, and add Tamil, Malayalam, Telugu and atleast 12 Bharatiya languages

2022-10-02 10:34 UTC, lostdesign commented
hi @soumyatheman thanks for your PR! 
I am about to merge #171 which adds new strings - could you add these already?

Regarding the other languages, sure go ahead! Thank you so much!
Also, would be cool if you can add the discord to discuss things there - I respond there much quicker!
https://discord.gg/uNjJzZvccr

2022-10-02 22:47 UTC, lostdesign requested changes
I just pushed the new translations, can you check the new format. Every translation now also has a `command` section and settings was extended with an `allowPrerelease` block. Thanks in advance.

2022-10-03 04:05 UTC, soumyatheman commented
Sorry, It's currently Durga Puja aka Sharad Navaratri going on. So, I am very busy, to enjoy the Puja. I'll be on work again after the Puja ends. Thanks for accepting my PR. ধন্যবাদ

2022-10-03 07:13 UTC, lostdesign commented
> Sorry, It's currently Durga Puja aka Sharad Navaratri going on. So, I am very busy, to enjoy the Puja. I'll be on work again after the Puja ends. Thanks for accepting my PR. ধন্যবাদ 

No worries! Enjoy your time and thanks for letting me know 🫶

2022-10-07 15:53 UTC, lostdesign commented
@soumyatheman good catch, fixed it and merged #181

2022-10-08 18:09 UTC, soumyatheman commented
All Done. I hope everything is fine now

2022-10-10 07:52 UTC, lostdesign requested changes

2022-10-10 07:52 UTC, lostdesign commented on README.md
> +### This is a request from the Bengali translator of this app to all the Bharatiya users using this project, if you can or have the knowledge of your language or Sanskrit, please let me know. So, tha
Could you move this into a discussion instead of a comment in the readme please? See https://github.com/lostdesign/linked/discussions/categories/01-general

2022-10-10 07:52 UTC, lostdesign commented on src/locales/bn-IN.json
> +      }
Could you format the json please?

2022-10-10 14:29 UTC, soumyatheman commented on README.md
> +### This is a request from the Bengali translator of this app to all the Bharatiya users using this project, if you can or have the knowledge of your language or Sanskrit, please let me know. So, tha
Okay I'll do so,

2022-10-10 14:30 UTC, soumyatheman commented on src/locales/bn-IN.json
> +      }
I think it's the same with en_US. I rechecked it, it's same with en_US. Please show me the error.(Highlight)

2022-10-11 06:48 UTC, lostdesign commented on src/locales/bn-IN.json
> +      }
<img width="181" alt="Bildschirmfoto 2022-10-11 um 08 48 36" src="https://user-images.githubusercontent.com/5164617/195016020-8b1e84ef-4975-45ff-8abc-4a64d3789172.png">

2022-10-15 14:28 UTC, merged

2022-10-15 14:29 UTC, lostdesign commented
I will fix it, all good. Merging your PR now - thanks :)

2022-10-15 14:40 UTC, soumyatheman commented
> I will fix it, all good. Merging your PR now - thanks :)

I'm extremely sorry for being late. My college has started after Durga Puja vacation ended, I was also ill for almost a week. So, extremely sorry.

2022-10-15 15:14 UTC, lostdesign commented
> > I will fix it, all good. Merging your PR now - thanks :)
> 
> 
> 
> I'm extremely sorry for being late. My college has started after Durga Puja vacation ended, I was also ill for almost a week. So, extremely sorry. 

No need to be sorry. I am grateful for your contribution and it is really a minor issue.

You've been helpful so don't worry. Enjoy your holidays!