:speech_balloon: Updated Readme
lostdesign/linked pull request #179
Opened 2022-10-02 22:37 UTC by NalinPlad

Changed header to HTML so that the content could be centered. I also slightly reduced the size of the image. One of the badges was broken so I replaced it as well.

2022-10-02 22:43 UTC, lostdesign requested changes
Can you remove the div and only use the img tags in the following order instead?

```html
<img width=90% src="https://user-images.githubusercontent.com/5164617/132354376-44ba85f3-bb21-448e-8c12-4e0fe9af2543.png" alt="Promotional Image"/>
<br>
<img alt="GitHub release (latest by date)" src="https://img.shields.io/github/v/release/lostdesign/linked">
<img alt="Project downloads" src="https://img.shields.io/github/downloads/lostdesign/linked/total"/>
<img alt="Discord" src="https://img.shields.io/discord/884747974859702352?label=discord"/>
<img alt="GitHub issues" src="https://img.shields.io/github/issues/lostdesign/linked">
```

2022-10-02 22:45 UTC, lostdesign requested changes

2022-10-02 22:45 UTC, lostdesign commented on README.md
> +**[You can download it here for free!](https://github.com/lostdesign/linked/releases/latest)**
I think it should stay linked in this case.

2022-10-02 22:52 UTC, NalinPlad commented on README.md
> +**[You can download it here for free!](https://github.com/lostdesign/linked/releases/latest)**
Sounds good

2022-10-02 22:57 UTC, NalinPlad commented
The div is neccesary to keep the images centered

2022-10-02 22:58 UTC, lostdesign commented
> The div is neccesary to keep the images centered

Not really a fan of it being centered tbh

2022-10-02 23:01 UTC, NalinPlad commented
I changed it, now the badges are on the left

2022-10-06 14:45 UTC, closed without merging

2022-10-06 17:52 UTC, NalinPlad commented
It's a minor change and not much reason to keep it up when there are more important pull requests to review. I'm not demanding for anyone to do anything