Isolated checkbox fixed issue#51
lostdesign/linked pull request #183
Opened 2022-10-08 14:19 UTC by CarlosPC94

We solved the problem about the isolated Checkboxes between the week days, as you can see in the following videos.

> Master branch is broken and u can't add checkboxes so we moved to the v1.4.13 release branch(tag) and we solved there.

### Before solving the problem:

https://user-images.githubusercontent.com/61242676/194711017-436cb78c-c2f0-4710-a902-dcd0230568b6.mov

### After solving the problem:

https://user-images.githubusercontent.com/61242676/194711065-cd42a497-76f6-4b5e-8613-98d7754a6803.mov

### Bugfix description:

We assing the getEditor() value into a new variable (aux) and then we clear the editor before assigning. When the editor object was set it with the new variable value (aux). Doing this the Checkboxes between week  days this are perfectly isolated.

2022-10-08 16:13 UTC, lostdesign commented
Hi thanks for your PR! Can you shortly tell me why you think that the master branch is broken?

2022-10-08 16:15 UTC, lostdesign requested changes

2022-10-08 16:15 UTC, lostdesign commented on src/components/editor.vue
> +        var aux = editor.getHTML();
Could you please use `const` and rename the variable to `data`?

2022-10-08 16:27 UTC, lostdesign requested changes

2022-10-08 16:27 UTC, lostdesign commented on src/components/editor.vue
> +        this.editor.commands.clearContent()
Okay I get what you mean by "master is broken". The current master itself is not broken, but this line breaks the new slash command interface. Can you look into it? 

I cannot merge this fix when it breaks the slash command.

2022-10-08 18:57 UTC, CarlosPC94 commented on src/components/editor.vue
> +        this.editor.commands.clearContent()
Oh I just saw in twiter how slash command should work, but in our computers it doesn't even without our changes, so ... we will try to know why doesn't work first and then we will try to solve it :)

2022-10-09 11:28 UTC, CarlosPC94 commented
### Final fix

We solved the issue in the master branch, we already fixed the bug that blocks the popup after writing the slash command on the editor PR: #185 

**IMPORTANT:** PR #185 fixing slash command must be merged before to see this funcionality working on new installations

Video with the issue solved:

https://user-images.githubusercontent.com/61242676/194754332-02dab1e3-3ac3-42fd-93d1-3306fb0e607d.mov

2022-10-09 12:17 UTC, lostdesign requested changes

2022-10-09 12:17 UTC, lostdesign commented on src/components/editor.vue
> +        this.editor.commands.clearContent()
![Bildschirmfoto 2022-10-09 um 14 15 39](https://user-images.githubusercontent.com/5164617/194756322-b06e76a2-6f46-4f49-b708-772c815c0c96.png)

Using the keyboard rather than the mouse breaks the slash command panel close.

2022-10-15 14:29 UTC, lostdesign commented
Any news on this?

2022-11-28 13:14 UTC, lostdesign commented
Hey, I'd close this PR. Please open a new PR once you continue on this. Thanks in advance :)

2022-11-28 13:14 UTC, closed without merging