🌐 add Korean translation
lostdesign/linked pull request #72
Opened 2021-06-24 23:26 UTC by sh9351

2021-06-25 07:03 UTC, lostdesign requested changes
So far so good unless the package.json change. Once reverted I will merge right away.

2021-06-25 07:03 UTC, lostdesign commented on package.json
> +  "version": "1.3.2",
Can you revert that change as I am usually bumping the version in a tag commit.

2021-06-26 00:56 UTC, sh9351 commented
Okay, I reverted the changes

2021-07-02 08:16 UTC, lostdesign commented
Alright thanks, sorry for not getting back to you earlier.

2021-07-02 08:16 UTC, merged