Feature/add days per week option
lostdesign/linked pull request #78
Opened 2021-08-06 15:21 UTC by sepiott

Adds the ability to choose a type of week, between the options of a standard 7 day week or a 5 day working week. 

There are also two fixes for the language switcher included: 
- The Dropdown wasn't shown, when there was no language saved in the local storage due to an javascript undefined variable error. 
- The Aria Parameter "activedescendant" and the list items id wasn't dynamicly set and therefor was the same for every option and id

2021-08-07 13:52 UTC, lostdesign commented
Thanks for your PR Seb, is it okay if I add electron-store beforehand in the next release as I really don't want to use the localstorage anymore? The recent language dropdown bug could have been prevented by a migration for example :D 

I am planning on adding the electron-store within the next two days. Could you then move the localstorage property into the electon-store option?

2021-08-09 07:36 UTC, lostdesign commented
Noticed a bug where using the keyboard or menu items to skip a single day would select saturday and sunday as it skips one day at a time. 

Could you implement to skip sat/sun when working week is selected? In both directions, so if monday and you go back, skip to friday, if friday, skip to monday.

2021-08-10 06:34 UTC, lostdesign requested changes
The electron-store had been pushed, you may now use that.

2021-08-10 06:34 UTC, lostdesign commented on src/components/day-switcher.vue
> +      justify-between
can we keep that justify-center, as i removed the width restriction and having the days loose would not really work well

<img width="936" alt="Bildschirmfoto 2021-08-10 um 08 29 58" src="https://user-images.githubusercontent.com/5164617/128819025-78719432-91c6-47f8-b3f4-5cf83f686d44.png">

2021-08-10 06:34 UTC, lostdesign commented on src/components/day-switcher.vue
> +      px-10
guess this might not be necessary then as well

2021-08-10 06:34 UTC, lostdesign commented on src/components/days-per-week-dropdown.vue
> +      selected: parseInt(localStorage.daysPerWeek) || 7,
You may now use `AppGetters.GET_DAYS_PER_WEEK` from vuex and need to store the value inside `electron-store`. You can take a look at how the theme is made, all necessary code is in the `<theme-switcher>` and `vuex/modules/app/..`

2021-08-10 06:34 UTC, lostdesign commented on src/components/days-per-week-dropdown.vue
> +      this.setCurrentWeek()
This only was necessary for the language changes, I guess you could remove it and it should work fine? I needed to rerender the day selectors as they are INTL based

2021-08-10 09:21 UTC, sepiott commented on src/components/days-per-week-dropdown.vue
> +      this.setCurrentWeek()
I tried it, but without this, the day-switcher will not chance, when the setting is changed

2021-08-10 10:39 UTC, lostdesign commented on src/components/days-per-week-dropdown.vue
> +      this.setCurrentWeek()
Ohh damn, you are right lol. It would recalculate the week. Without it would not mutate the week.

2021-08-19 18:03 UTC, lostdesign requested changes
Changing days didn't work per shortcut, as `this.isWorkWeek()` was called as function while it is a computed property.

2022-02-05 17:50 UTC, closed without merging